default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: dispensed_development

test:
  <<: *default
  database: dispensed_test

production:
  primary: &production_primary
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
  cache:
    <<: *production_primary
    database_tasks: false
  queue:
    <<: *production_primary
    database_tasks: false
